services:
  app:
    build: .
    image: ms-producao
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: database
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_ADDR: 0.0.0.0

  jwt_token_mock:
    build:
      context: doubles/jwt_token_mock/
    ports:
      - 3001:3001
    env_file:
      - .env