apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-ms-producao
spec:
  provider: aws
  secretObjects:
  - data:
    - key: typeorm
      objectName: dbcredentials
      jmesPath: typeorm
    secretName: db-secret
    type: Opaque
  parameters:
    objects: |
        - objectName: "dbcredentials"
          objectType: "secretsmanager"