apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-ms-producao
spec:
  provider: aws
  #secretObjects:
  #- data:
    #- key: typeormurl
    #  objectName: typeormurl
   # secretName: db-secret
  #  type: Opaque
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:851725345801:secret:dbcredentials-8lRmKA"
          objectType: "secretsmanager"
          jmesPath:
            - path: typeorm
              objectAlias: typeormurl
